load("//macros:jetpad_module.bzl", "jetpad_module")

jetpad_module(
  deps = [
     "//util/geometry:jar",
     "//util/base:jar",
     "@com_google_guava//jar"
  ],
  suite = "jetbrains.jetpad.model.AllTests"
)