java_library(
  name = "jar",
  srcs = glob(["src/main/java/**/*.java"]),
  deps = [
    "//mapper:jar",
    "//model:jar",
    "//gwt-util:jar",
    "//util/base:jar",

    "@com_google_gwt_user//jar",
    "@com_googlecode_gwtquery//jar"
  ],
  visibility = ["//visibility:public"]
)
