java_library(
  name = "jar",
  srcs = glob(["src/main/java/**/*.java"]),
  deps = [
    "//mapper:jar",
    "//model:jar",
    "//gwt-util:jar",
    "//util/base:jar",

    "//lib:gwt_user",
    "//lib:gwt_query"
  ],
  visibility = ["//visibility:public"]
)