java_library(
  name = "jar",
  srcs = glob(["src/main/java/**/*.java"]),
  deps = [
    "@com_google_guava//jar",
    "@com_google_gwt_user//jar",
    "@com_google_code_findbugs_annotations//jar"
  ],
  visibility = ["//visibility:public"]
)