load("//macros:jetpad_module.bzl", "jetpad_module")

jetpad_module(
  deps = [
    "//lib:guava",
    "//lib:findbug_annotations",
    "//lib:gwt_user"
  ],
  suite = "jetbrains.jetpad.json.AllTests"
)