load("//macros:jetpad_module.bzl", "jetpad_module")

jetpad_module(
  deps = [
    "@com_google_guava//jar",
    "@com_google_gwt_user//jar",
    "@com_google_code_findbugs_annotations//jar"
  ],
  suite = "jetbrains.jetpad.json.AllTests"
)