load("//macros:jetpad_module.bzl", "jetpad_module")

jetpad_module(
  deps = [
     "//util/base:jar",
     "//model:jar",
     "//mapper:jar",
     "//util/geometry:jar",

     "@com_googlecode_gwtquery//jar",
     "@com_google_gwt_user//jar",
     "@com_google_gwt_elemental//jar"
   ]
)