java_library(
  name = "findbug_annotations",
  exports = [
    "@com_google_code_findbugs_annotations//jar"
  ],
  visibility = ["//visibility:public"]
)

java_library(
  name = "guava",
  runtime_deps = [":findbug_annotations"],
  exports = [
    "@com_google_guava//jar",
    "@com_google_guava_gwt//jar",

    "@com_google_errorprone//jar",
    "@com_google_j2obj_annotations//jar"
  ],
  visibility = ["//visibility:public"]
)

java_library(
  name = "gwt_user",
  exports = [
    "@com_google_gwt_user//jar"
  ],
  visibility = ["//visibility:public"]
)

java_library(
  name = "junit",
  exports = [
    "@junit//jar"
  ],
  visibility = ["//visibility:public"]
)

java_library(
  name = "gwt_query",
  exports = [
    "@com_googlecode_gwtquery//jar",
  ],
  visibility = ["//visibility:public"]
)

java_library(
  name = "mockito",
  exports = [
    "@org_mockito//jar",
  ],
  visibility = ["//visibility:public"]
)