load("//macros:jetpad_module.bzl", "jetpad_module")

jetpad_module(
  deps = [
    "//util/base:jar",
    "//model:jar",
    "@com_google_guava//jar"
  ],
  suite = "jetbrains.jetpad.mapper.AllTests"
)