java_library(
  name = "jar",
  srcs = glob(["src/main/java/**/*.java"]),
  deps = [
    "//util/base:jar",
    "//model:jar",

    "@com_google_guava//jar"
  ],
  visibility = ["//visibility:public"]
)